// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class MatchSettlementModuleBindings
    {
        readonly ICloudCodeService k_Service;

        public MatchSettlementModuleBindings() : this(CloudCodeService.Instance) { }

        public MatchSettlementModuleBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<string> SettleMatch(string sessionId, int matchNumber, string winnerPlayerId)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "PongBackend",
                "SettleMatch",
                new Dictionary<string, object>()
                {
                    {"sessionId", sessionId},
                    {"matchNumber", matchNumber},
                    {"winnerPlayerId", winnerPlayerId},
                });
        }
    }
}
